// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVcrIFrmVf13psZpVA2J7muFZHm7gSG3w',
    appId: '1:967043426943:android:eda0bc67be453cf10f2d4a',
    messagingSenderId: '967043426943',
    projectId: 'flutter-project-6883f',
    databaseURL: 'https://flutter-project-6883f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-6883f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGrQ0r_-6AOuSrU8AnHe0gC08ovFmPs2Y',
    appId: '1:967043426943:ios:e7eac2a121218d090f2d4a',
    messagingSenderId: '967043426943',
    projectId: 'flutter-project-6883f',
    databaseURL: 'https://flutter-project-6883f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-6883f.appspot.com',
    iosClientId: '967043426943-mgslh7vroal9qfrqtj7mmp03nn5r29gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFlutterFirebase',
  );
}
